export const DETAIL_START = "DETAIL_START";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_ERROR = "DETAIL_ERROR";
// Job Order Action
export const JOB_ORDER_START = "JOB_ORDER_START";
export const JOB_ORDER_SUCCESS = "JOB_ORDER_SUCCESS";
export const JOB_ORDER_ERROR = "JOB_ORDER_ERROR";

// Performance Action
export const PERFORMANCE_START = "PERFORMANCE_START";
export const PERFORMANCE_SUCCESS = "PERFORMANCE_SUCCESS";
export const PERFORMANCE_ERROR = "PERFORMANCE_ERROR";

// Contact Action
export const CONTACT_SUBMIT_START = "CONTACT_SUBMIT_START";
export const CONTACT_SUBMIT_SUCCESS = "CONTACT_SUBMIT_SUCCESS";
export const CONTACT_SUBMIT_ERROR = "CONTACT_SUBMIT_ERROR";

// WalletBalance Action
export const GET_BALANCE_START = "GET_BALANCE_START";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_ERROR = "GET_BALANCE_ERROR";

// model Action
export const GET_ALL_MODEL_START = "GET_ALL_MODEL_START";
export const GET_ALL_MODEL_SUCCESS = "GET_ALL_MODEL_SUCCESS";
export const GET_ALL_MODEL_ERROR = "GET_ALL_MODEL_ERROR";


// model Action
export const GET_PURCHASED_MODEL_START = "GET_PURCHASED_MODEL_START";
export const GET_PURCHASED_MODEL_SUCCESS = "GET_PURCHASED_MODEL_SUCCESS";
export const GET_PURCHASED_MODEL_ERROR = "GET_PURCHASED_MODEL_ERROR";


export const PURCHASE_MODEL_START = "PURCHASE_MODEL_START";
export const PURCHASE_MODEL_SUCCESS = "PURCHASE_MODEL_SUCCESS";
export const PURCHASE_MODEL_ERROR = "PURCHASE_MODEL_ERROR";


// connect Action
export const CONNECT_WALLET_START = "CONNECT_WALLET_START";
export const CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS";
export const CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR";


// disconnect Action
export const DISCONNECT_WALLET_SUCCESS = "DISCONNECT_WALLET_SUCCESS";



export const ERROR_POPUP_START = "ERROR_POPUP_START";
export const ERROR_POPUP_STOP = "ERROR_POPUP_STOP";

export const UI_LOADER_START = "UI_LOADER_START";
export const UI_LOADER_STOP = "UI_LOADER_STOP";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";




export const AUTO_SNAP_START = "AUTO_SNAP_START";
export const AUTO_SNAP_SUCCESS = "AUTO_SNAP_SUCCESS";
export const AUTO_SNAP_ERROR = "AUTO_SNAP_ERROR";


// Video call Actions

export const GENERATE_QUICK_CALL_LINK_START = "GENERATE_QUICK_CALL_LINK_START";
export const GENERATE_QUICK_CALL_LINK_SUCCESS =
  "GENERATE_QUICK_CALL_LINK_SUCCESS";
export const GENERATE_QUICK_CALL_LINK_ERROR = "GENERATE_QUICK_CALL_LINK_ERROR";

export const SCHEDULE_APPOINMENT_START = "SCHEDULE_APPOINMENT_START";
export const SCHEDULE_APPOINMENT_SUCCESS = "SCHEDULE_APPOINMENT_SUCCESS";
export const SCHEDULE_APPOINMENT_ERROR = "SCHEDULE_APPOINMENT_ERROR";

export const FETCH_IMAGE_START = "FETCH_IMAGE_START";
export const FETCH_IMAGE_SUCCESS = "FETCH_IMAGE_SUCCESS";
export const FETCH_IMAGE_ERROR = "FETCH_IMAGE_ERROR";

export const DOWNLOAD_IMAGE_START = "DOWNLOAD_IMAGE_START";
export const DOWNLOAD_IMAGE_SUCCESS = "DOWNLOAD_IMAGE_SUCCESS";
export const DOWNLOAD_IMAGE_ERROR = "DOWNLOAD_IMAGE_ERROR";

export const FETCH_RECORDINGS_START = "FETCH_RECORDINGS_START";
export const FETCH_RECORDINGS_SUCCESS = "FETCH_RECORDINGS_SUCCESS";
export const FETCH_RECORDINGS_ERROR = "FETCH_RECORDINGS_ERROR";

export const DOWNLOAD_RECORDING_START = "DOWNLOAD_RECORDING_START";
export const DOWNLOAD_RECORDING_SUCCESS = "DOWNLOAD_RECORDING_SUCCESS";
export const DOWNLOAD_RECORDING_ERROR = "DOWNLOAD_RECORDING_ERROR";

export const FETCH_NOTES_START = "FETCH_NOTES_START";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_ERROR = "FETCH_NOTES_ERROR";
export const GET_CONFIGURATION_DETAIL_START = "GET_CONFIGURATION_DETAIL_START";
export const GET_CONFIGURATION_DETAIL_SUCCESS =
  "GET_CONFIGURATION_DETAIL_SUCCESS";
export const GET_CONFIGURATION_DETAIL_ERROR = "GET_CONFIGURATION_DETAIL_ERROR";

export const FETCH_DETAILS_START = "FETCH_DETAILS_START";
export const FETCH_DETAILS_SUCCESS = "FETCH_DETAILS_SUCCESS";
export const FETCH_DETAILS_ERROR = "FETCH_DETAILS_ERROR";

export const FETCH_CALL_DETAILS_START = "FETCH_CALL_DETAILS_START";
export const FETCH_CALL_DETAILS_SUCCESS = "FETCH_CALL_DETAILS_SUCCESS";
export const FETCH_CALL_DETAILS_ERROR = "FETCH_CALL_DETAILS_ERROR";

export const COMPLETE_JOBORDER_START = "COMPLETE_JOBORDER_START";
export const COMPLETE_JOBORDER_SUCCESS = "COMPLETE_JOBORDER_SUCCESS";
export const COMPLETE_JOBORDER_ERROR = "COMPLETE_JOBORDER_ERROR";

export const MEASUREMENT_JSON_START = "MEASUREMENT_JSON_START";
export const MESUREMENT_JSON_SUCCESS = "MESUREMENT_JSON_SUCCESS";
export const MESUREMENT_JSON_ERROR = "MESUREMENT_JSON_ERROR";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";




export const FETCH_TOKEN_START = "FETCH_TOKEN_START";
export const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS";
export const FETCH_TOKEN_ERROR = "FETCH_TOKEN_ERROR";

export const FETCH_PROFILEDETAILS_START = "FETCH_PROFILEDETAILS_START";
export const FETCH_PROFILEDETAILS_SUCCESS = "FETCH_PROFILEDETAILS_SUCCESS";
export const FETCH_PROFILEDETAILS_ERROR = "FETCH_PROFILEDETAILS_ERROR";

export const UPDATE_PROFILEDETAILS_START = "UPDATE_PROFILEDETAILS_START";
export const UPDATE_PROFILEDETAILS_SUCCESS = "UPDATEH_PROFILEDETAILS_SUCCESS";
export const UPDATE_PROFILEDETAILS_ERROR = "UPDATE_PROFILEDETAILS_ERROR";




export const GET_QUESTIONNAIRE_START = "GET_QUESTIONNAIRE_START";
export const GET_QUESTIONNAIRE_SUCCESS = "GET_QUESTIONNAIRE_SUCCESS";
export const GET_QUESTIONNAIRE_ERROR = "GET_QUESTIONNAIRE_ERROR";

export const UI_NAV_TOGGLE = "UI_NAV_TOGGLE";

export const DELETE_IMAGE_START = "DELETE_IMAGE_START";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_ERROR = "DELETE_IMAGE_ERROR";

export const ADD_CACHED_CAPTURED_IMAGE = "ADD_CACHED_CAPTURED_IMAGE";
export const DELETE_CACHED_CAPTURED_IMAGE = "DELETE_CACHED_CAPTURED_IMAGE";

export const FETCH_RELAR_START = "FETCH_RELAR_START";

export const FETCH_RELAR_SUCCESS = "FETCH_RELAR_SUCCESS";

export const FETCH_RELAR_ERROR = "FETCH_RELAR_ERROR";

export const FETCH_FLOOR_START = "FETCH_FLOOR_START";

export const FETCH_FLOOR_SUCCESS = "FETCH_FLOOR_SUCCESS";

export const FETCH_FLOOR_ERROR = "FETCH_FLOOR_ERROR";

export const FETCH_LINK_START = "FETCH_LINK_START";
export const FETCH_LINK_SUCCESS = "FETCH_LINK_SUCCESS";
export const FETCH_LINK_ERROR = "FETCH_LINK_ERROR";

export const FETCH_FLOORPLANS_START = "FETCH_FLOORPLAN_START";
export const FETCH_FLOORPLANS_SUCCESS = "FETCH_FLOORPLAN_SUCCESS";
export const FETCH_FLOORPLANS_ERROR = "FETCH_FLOORPLAN_ERROR";

// Download Zip
export const DOWNLOAD_ZIP_START = "DOWNLOAD_ZIP_START";
export const DOWNLOAD_ZIP_SUCCESS = "DOWNLOAD_ZIP_SUCCESS";
export const DOWNLOAD_ZIP_ERROR = "DOWNLOAD_ZIP_ERROR";

// Technician Job Order Action
export const TECHNICIAN_JOB_ORDER_START = "TECHNICIAN_JOB_ORDER_START";
export const TECHNICIAN_JOB_ORDER_SUCCESS = "TECHNICIAN_JOB_ORDER_SUCCESS";
export const TECHNICIAN_JOB_ORDER_ERROR = "TECHNICIAN_JOB_ORDER_ERROR";

// Floor Scan list based on job order id
export const FLOOR_SCAN_START = "FLOOR_SCAN_START";
export const FLOOR_SCAN_SUCCESS = "FLOOR_SCAN_SUCCESS";
export const FLOOR_SCAN_ERROR = "FLOOR_SCAN_ERROR";

// Floor Scan list based on job order id
export const FLOOR_SCAN_DETAIL_START = "FLOOR_SCAN_DETAIL_START";
export const FLOOR_SCAN_DETAIL_SUCCESS = "FLOOR_SCAN_DETAIL_SUCCESS";
export const FLOOR_SCAN_DETAIL_UNMOUNT = "FLOOR_SCAN_DETAIL_UNMOUNT";
export const FLOOR_SCAN_DETAIL_ERROR = "FLOOR_SCAN_DETAIL_ERROR";

export const UPDATE_FLOOR_SCAN_IMAGE_START = "UPDATE_FLOOR_SCAN_IMAGE_START";
export const UPDATE_FLOOR_SCAN_IMAGE_SUCCESS =
  "UPDATE_FLOOR_SCAN_IMAGE_SUCCESS";
export const UPDATE_FLOOR_SCAN_IMAGE_ERROR = "UPDATE_FLOOR_SCAN_IMAGE_ERROR";

export const PLY_RETRY_START = "PLY_RETRY_START";
export const PLY_RETRY_SUCCESS = "PLY_RETRY_SUCCESS";
export const PLY_RETRY_ERROR = "PLY_RETRY_ERROR";
// Floor Scan list based on job order id
export const FLOOR_SCAN_UPDATE_STATUS_START = "FLOOR_SCAN_UPDATE_STATUS_START";
export const FLOOR_SCAN_UPDATE_STATUS_SUCCESS =
  "FLOOR_SCAN_UPDATE_STATUS_SUCCESS";
export const FLOOR_SCAN_UPDATE_STATUS_ERROR = "FLOOR_SCAN_UPDATE_STATUS_ERROR";

export const AVAILABLE_MEASUREMENT_START = "AVAILABLE_MEASUREMENT_START";
export const AVAILABLE_MEASUREMENT_SUCCESS = "AVAILABLE_MEASUREMENT_SUCCESS";
export const AVAILABLE_MEASUREMENT_ERROR = "AVAILABLE_MEASUREMENT_ERROR";

export const FLOOR_SCAN_INDEX_START = "FLOOR_SCAN_INDEX_START";
export const FLOOR_SCAN_INDEX_SUCCESS = "FLOOR_SCAN_INDEX_SUCCESS";
export const FLOOR_SCAN_INDEX_ERROR = "FLOOR_SCAN_INDEX_ERROR";



export const FLOORSCAN_JSONS_START = "FLOORSCAN_JSONS_START";
export const FLOORSCAN_JSONS_SUCCESS = "FLOORSCAN_JSONS_SUCCESS";
export const FLOORSCAN_JSONS_ERROR = "FLOORSCAN_JSONS_ERROR";
