export const countries = [{ id: "USA", name: "USA" }];
export const states = [
  { id: "Alabama", name: "Alabama" },
  { id: "Alaska", name: "Alaska" },
  { id: "Arizona", name: "Arizona" },
  { id: "Arkansas", name: "Arkansas" },
  { id: "California", name: "California" },
  { id: "Colorado", name: "Colorado" },
  { id: "Connecticut", name: "Connecticut" },
  { id: "Delaware", name: "Delaware" },
  { id: "District of Columbia", name: "District of Columbia" },
  { id: "Florida", name: "Florida" },
  { id: "Georgia", name: "Georgia" },
  { id: "Hawaii", name: "Hawaii" },
  { id: "Idaho", name: "Idaho" },
  { id: "Illinois", name: "Illinois" },
  { id: "Indiana", name: "Indiana" },
  { id: "Iowa", name: "Iowa" },
  { id: "Kansas", name: "Kansas" },
  { id: "Kentucky", name: "Kentucky" },
  { id: "Louisiana", name: "Louisiana" },
  { id: "Maine", name: "Maine" },
  { id: "Maryland", name: "Maryland" },
  { id: "Massachusetts", name: "Massachusetts" },
  { id: "Michigan", name: "Michigan" },
  { id: "Minnesota", name: "Minnesota" },
  { id: "Mississippi", name: "Mississippi" },
  { id: "Missouri", name: "Missouri" },
  { id: "Montana", name: "Montana" },
  { id: "Nebraska", name: "Nebraska" },
  { id: "Nevada", name: "Nevada" },
  { id: "New Hampshire", name: "New Hampshire" },
  { id: "New Jersey", name: "New Jersey" },
  { id: "New Mexico", name: "New Mexico" },
  { id: "New York", name: "New York" },
  { id: "North Carolina", name: "North Carolina" },
  { id: "North Dakota", name: "North Dakota" },
  { id: "Ohio", name: "Ohio" },
  { id: "Oklahoma", name: "Oklahoma" },
  { id: "Oregon", name: "Oregon" },
  { id: "Pennsylvania", name: "Pennsylvania" },
  { id: "Rhode Island", name: "Rhode Island" },
  { id: "South Carolina", name: "South Carolina" },
  { id: "South Dakota", name: "South Dakota" },
  { id: "Tennessee", name: "Tennessee" },
  { id: "Texas", name: "Texas" },
  { id: "Utah", name: "Utah" },
  { id: "Vermont", name: "Vermont" },
  { id: "Virginia", name: "Virginia" },
  { id: "Washington", name: "Washington" },
  { id: "West Virginia", name: "West Virginia" },
  { id: "Wisconsin", name: "Wisconsin" },
  { id: "Wyoming", name: "Wyoming" },
];

// here key are same but values are different so valAppraiser is for Appraiser and valTechnician is for Technician
export const floorScanStatusEnum = [
  {
    id: "VIDEO_CAPTURED",
    valAppraiser: "Video Captured",
    valTechnician: "Video Captured",
    color: "blue",
  },
  {
    id: "PLY_AVAILABLE",
    valAppraiser: "Ply Available",
    valTechnician: "Ply Available",
    color: "red",
  },
  {
    id: "PLY_FAILED",
    valAppraiser: "Ply Failed",
    valTechnician: "Ply Failed",
    color: "red",
  },
  {
    id: "FLOORPLAN_AVAILABLE",
    valAppraiser: "Floor Plan Available",
    valTechnician: "Floor Plan Available",
    color: "orange",
  },
  {
    id: "FLOORPLAN_FAILED",
    valAppraiser: "Rescan Requested",
    valTechnician: "Request Rescan",
    color: "green",
  },
  {
    id: "COMPLETED",
    valAppraiser: "Completed",
    valTechnician: "Completed",
    color: "green",
  },
  {
    id: "2D_COMPLETED",
    valAppraiser: "2D Completed",
    valTechnician: "2D Completed",
    color: "green",
  },
  {
    id: "3D_COMPLETED",
    valAppraiser: "3D Completed",
    valTechnician: "3D Completed",
    color: "green",
  },
];

export const floorName = [
  { id: 0, value: "3rd Basement" },
  { id: 1, value: "2nd Basement" },
  { id: 2, value: "Basement" },
  { id: 3, value: "Ground Floor" },
  { id: 4, value: "Exterior" },
  { id: 5, value: "1st Floor" },
  { id: 6, value: "2nd Floor" },
  { id: 7, value: "3rd Floor" },
  { id: 8, value: "4th Floor" },
  { id: 9, value: "5th Floor" },
  { id: 10, value: "6th Floor" },
  { id: 11, value: "7th Floor" },
  { id: 12, value: "8th Floor" },
  { id: 13, value: "9th Floor" },
  { id: 14, value: "10th Floor" },
  { id: 15, value: "11th Floor" },
  { id: 16, value: "12th Floor" },
  { id: 17, value: "13th Floor" },
  { id: 18, value: "14th Floor" },
  { id: 19, value: "15th Floor" },
  { id: 20, value: "16th Floor" },
  { id: 21, value: "17th Floor" },
  { id: 22, value: "18th Floor" },
  { id: 23, value: "19th Floor" },
  { id: 24, value: "20th Floor" },
  { id: 25, value: "21st Floor" },
  { id: 26, value: "22nd Floor" },
  { id: 27, value: "23rd Floor" },
  { id: 28, value: "24th Floor" },
  { id: 29, value: "25th Floor" },
  { id: 30, value: "26th Floor" },
  { id: 31, value: "27th Floor" },
  { id: 32, value: "28th Floor" },
  { id: 33, value: "29th Floor" },
  { id: 34, value: "30th Floor" },
  { id: 35, value: "31st Floor" },
  { id: 36, value: "32nd Floor" },
  { id: 37, value: "33rd Floor" },
  { id: 38, value: "34th Floor" },
  { id: 39, value: "35th Floor" },
  { id: 40, value: "36th Floor" },
  { id: 41, value: "37th Floor" },
  { id: 42, value: "38th Floor" },
  { id: 43, value: "39th Floor" },
  { id: 44, value: "40th Floor" },
  { id: 45, value: "41st Floor" },
  { id: 46, value: "42nd Floor" },
  { id: 47, value: "43rd Floor" },
  { id: 48, value: "44th Floor" },
  { id: 49, value: "45th Floor" },
  { id: 50, value: "46th Floor" },
  { id: 51, value: "47th Floor" },
  { id: 52, value: "48th Floor" },
  { id: 53, value: "49th Floor" },
  { id: 54, value: "50th Floor" },
  { id: 55, value: "Roof" },
];

export const areaLabel = [
  { id: "Kitchen", value: "Kitchen" },
  { id: "Dining", value: "Dining" },
  { id: "Living Room", value: "Living Room" },
  { id: "Hall", value: "Hall" },
  { id: "Master Bedroom", value: "Master Bedroom" },
  { id: "Bedroom", value: "Bedroom" },
  { id: "Bath", value: "Bath" },
  { id: "Closet", value: "Closet" },
  { id: "Study", value: "Study" },
  { id: "Music Room", value: "Music Room" },
  { id: "Balcony", value: "Balcony" },
  { id: "Garage", value: "Garage" },
  { id: "Hallway", value: "Hallway" },
  { id: "Laundry Room", value: "Laundry Room" },
  { id: "Playroom", value: "Playroom" },
  { id: "Cellar", value: "Cellar" },
  { id: "Den", value: "Den" },
  { id: "WorkShop", value: "WorkShop" },
  { id: "Stairway", value: "Stairway" },
  { id: "Furnace Room", value: "Furnace Room" },
  { id: "Toilet", value: "Toilet" },
  { id: "Vestibule", value: "Vestibule" },
  { id: "Deck", value: "Deck" },
  { id: "Patio", value: "Patio" },
  { id: "Porch", value: "Porch" },
  { id: "Outbuilding", value: "Outbuilding" },
  { id: "Unfinished Basement", value: "Unfinished Basement" },
  { id: "Master Bathroom", value: "Master Bathroom" },
  { id: "Attic / Loft", value: "Attic / Loft" },
  { id: "Other", value: "Other" },
];

export const floorScanType = [
  { id: 1, value: "LIDAR" },
  { id: 2, value: "NON_LIDAR" },
];

export const undoLineFor3D = [
  { id: 1, value: "door" },
  { id: 2, value: "window" },
  { id: 3, value: "line" },
  { id: 4, value: "label" },
];

export const additionalType3D = [
  { id: "0", value: "Add as additional" },
  { id: "1", value: "Add as non additional" },
];
